# Generated by Django 6.0.1 on 2026-01-27 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='delimiter',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls', 'xml'])]),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV File'), ('excel', 'Excel File'), ('xml', 'XML File')], default='csv', max_length=10),
        ),
    ]
