# Generated by Django 6.0.1 on 2026-01-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_manager', '0002_remove_datasource_delimiter_alter_datasource_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rows', models.IntegerField(default=0)),
                ('total_columns', models.IntegerField(default=0)),
                ('column_types', models.JSONField(default=dict)),
                ('basic_stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='data_manager.datasource')),
            ],
        ),
    ]
